import { StageItem } from '../types/stadium';

export const STAGE_CATEGORIES = ['밴드', '댄스', '힙합', '응원단', '기타'] as const;

export const STAGE_TIMETABLE: StageItem[] = [
  {
    school: 'GIST',
    clubName: 'PULSE (댄스동아리)',
    category: '댄스',
    genre: 'K-POP',
    songTitle: 'Supernova - aespa (Cover)',
    startHour: 14,
    startMinute: 0,
    endHour: 15,
    endMinute: 0,
  },
  {
    school: 'UNIST',
    clubName: 'MELODY (밴드)',
    category: '밴드',
    genre: '모던락',
    songTitle: '한 페이지가 될 수 있게 - DAY6',
    startHour: 15,
    startMinute: 0,
    endHour: 16,
    endMinute: 0,
  },
  {
    school: 'DGIST',
    clubName: 'BEAT (힙합)',
    category: '힙합',
    genre: '스트릿',
    songTitle: '자작곡 & 사이퍼 쇼케이스',
    startHour: 16,
    startMinute: 0,
    endHour: 17,
    endMinute: 15,
  },
  {
    school: 'POSTECH',
    clubName: '스틸러 (Steeler)',
    category: '밴드',
    genre: '락',
    songTitle: '사건의 지평선 - 윤하 (Cover)',
    startHour: 17,
    startMinute: 15,
    endHour: 18,
    endMinute: 0,
  },
  {
    school: 'KAIST',
    clubName: 'CHORUS (보컬동아리)',
    category: '응원단',
    genre: '아카펠라 & 발라드',
    songTitle: 'STadium 축하합창 메들리',
    startHour: 18,
    startMinute: 0,
    endHour: 19,
    endMinute: 0,
  },
  {
    school: 'POSTECH',
    clubName: 'STadium 초청가수 특별공연',
    category: '기타',
    genre: '메인 축하공연',
    songTitle: '2026 STadium 피날레 콘서트',
    startHour: 20,
    startMinute: 0,
    endHour: 21,
    endMinute: 0,
  },
];
