import { RawScheduledMatch } from '../types/stadium';

export const DEFAULT_RAW_SCHEDULE_FLAT: RawScheduledMatch[] = [
  // Soccer
  {
    id: 'soc-1',
    sportKey: 'soccer',
    sportName: '축구',
    icon: '⚽',
    team1: 'GIST',
    team2: 'UNIST',
    startHour: 10,
    startMinute: 0,
    endHour: 11,
    endMinute: 30,
    venue: '대운동장',
    round: '8강 1경기',
    score1Final: 2,
    score2Final: 1,
    winningTeamFinal: 'GIST',
  },
  {
    id: 'soc-2',
    sportKey: 'soccer',
    sportName: '축구',
    icon: '⚽',
    team1: 'KAIST',
    team2: 'DGIST',
    startHour: 12,
    startMinute: 0,
    endHour: 13,
    endMinute: 30,
    venue: '대운동장',
    round: '준결승 1경기',
    score1Final: 3,
    score2Final: 1,
    winningTeamFinal: 'KAIST',
  },
  {
    id: 'soc-3',
    sportKey: 'soccer',
    sportName: '축구',
    icon: '⚽',
    team1: 'POSTECH',
    team2: 'KAIST',
    startHour: 17,
    startMinute: 0,
    endHour: 18,
    endMinute: 30,
    venue: '대운동장',
    round: '준결승 2경기',
    score1Final: 2,
    score2Final: 1,
    winningTeamFinal: 'POSTECH',
  },
  {
    id: 'soc-4',
    sportKey: 'soccer',
    sportName: '축구',
    icon: '⚽',
    team1: 'POSTECH',
    team2: 'GIST',
    startHour: 19,
    startMinute: 0,
    endHour: 20,
    endMinute: 30,
    venue: '대운동장',
    round: '결승전',
    score1Final: 3,
    score2Final: 2,
    winningTeamFinal: 'POSTECH',
  },

  // Baseball
  {
    id: 'bb-1',
    sportKey: 'baseball',
    sportName: '야구',
    icon: '⚾',
    team1: 'DGIST',
    team2: 'GIST',
    startHour: 9,
    startMinute: 30,
    endHour: 12,
    endMinute: 0,
    venue: '곡강 야구장',
    round: '예선 1경기',
    score1Final: 4,
    score2Final: 2,
    winningTeamFinal: 'DGIST',
  },
  {
    id: 'bb-2',
    sportKey: 'baseball',
    sportName: '야구',
    icon: '⚾',
    team1: 'POSTECH',
    team2: 'KAIST',
    startHour: 16,
    startMinute: 30,
    endHour: 18,
    endMinute: 30,
    venue: '포항야구장',
    round: '본선 메인 매치',
    score1Final: 5,
    score2Final: 3,
    winningTeamFinal: 'POSTECH',
  },
  {
    id: 'bb-3',
    sportKey: 'baseball',
    sportName: '야구',
    icon: '⚾',
    team1: 'UNIST',
    team2: 'KENTECH',
    startHour: 19,
    startMinute: 0,
    endHour: 21,
    endMinute: 0,
    venue: '포항야구장',
    round: '순위 결정전',
    score1Final: 2,
    score2Final: 1,
    winningTeamFinal: 'UNIST',
  },

  // LoL
  {
    id: 'lol-1',
    sportKey: 'lol',
    sportName: 'LoL',
    icon: '🎮',
    team1: 'POSTECH',
    team2: 'GIST',
    startHour: 11,
    startMinute: 0,
    endHour: 13,
    endMinute: 0,
    venue: '콜로세움',
    round: '8강 BO3',
    score1Final: 2,
    score2Final: 0,
    winningTeamFinal: 'POSTECH',
  },
  {
    id: 'lol-2',
    sportKey: 'lol',
    sportName: 'LoL',
    icon: '🎮',
    team1: 'KAIST',
    team2: 'UNIST',
    startHour: 17,
    startMinute: 15,
    endHour: 18,
    endMinute: 45,
    venue: '콜로세움',
    round: '4강 BO3',
    score1Final: 2,
    score2Final: 1,
    winningTeamFinal: 'KAIST',
  },
  {
    id: 'lol-3',
    sportKey: 'lol',
    sportName: 'LoL',
    icon: '🎮',
    team1: 'POSTECH',
    team2: 'KAIST',
    startHour: 19,
    startMinute: 15,
    endHour: 21,
    endMinute: 45,
    venue: '콜로세움',
    round: '결승 BO5',
    score1Final: 3,
    score2Final: 1,
    winningTeamFinal: 'POSTECH',
  },

  // Badminton (배드민턴)
  {
    id: 'bad-1',
    sportKey: 'badminton',
    sportName: '배드민턴',
    icon: '🏸',
    team1: 'GIST',
    team2: 'UNIST',
    startHour: 11,
    startMinute: 0,
    endHour: 13,
    endMinute: 0,
    venue: '체육관 B코트',
    round: '배드민턴 예선 1경기',
    score1Final: 3,
    score2Final: 1,
    winningTeamFinal: 'GIST',
  },
  {
    id: 'bad-2',
    sportKey: 'badminton',
    sportName: '배드민턴',
    icon: '🏸',
    team1: 'POSTECH',
    team2: 'KAIST',
    startHour: 17,
    startMinute: 0,
    endHour: 18,
    endMinute: 30,
    venue: '체육관 B코트',
    round: '배드민턴 라이벌전',
    score1Final: 3,
    score2Final: 2,
    winningTeamFinal: 'POSTECH',
  },

  // Basketball (농구)
  {
    id: 'bk-1',
    sportKey: 'basketball',
    sportName: '농구',
    icon: '🏀',
    team1: 'POSTECH',
    team2: 'KAIST',
    startHour: 13,
    startMinute: 30,
    endHour: 15,
    endMinute: 30,
    venue: '체육관 A코트',
    round: '농구 본선 1경기',
    score1Final: 68,
    score2Final: 62,
    winningTeamFinal: 'POSTECH',
  },
  {
    id: 'bk-2',
    sportKey: 'basketball',
    sportName: '농구',
    icon: '🏀',
    team1: 'KAIST',
    team2: 'UNIST',
    startHour: 17,
    startMinute: 0,
    endHour: 19,
    endMinute: 0,
    venue: '체육관 A코트',
    round: '농구 준결승전',
    score1Final: 58,
    score2Final: 52,
    winningTeamFinal: 'KAIST',
  },
  {
    id: 'bk-3',
    sportKey: 'basketball',
    sportName: '농구',
    icon: '🏀',
    team1: 'DGIST',
    team2: 'KENTECH',
    startHour: 19,
    startMinute: 30,
    endHour: 21,
    endMinute: 0,
    venue: '체육관 A코트',
    round: '농구 순위결정전',
    score1Final: 55,
    score2Final: 49,
    winningTeamFinal: 'DGIST',
  },
];
