import { School } from '../types/stadium';

export const SCHOOLS: Record<string, School> = {
  POSTECH: {
    id: 'POSTECH',
    name: '포항공과대학교',
    shortName: 'POSTECH',
    logoText: 'P',
    logoUrl: '/postech.png',
    color: '#A61955',
    bgLight: '#FFF0F5',
    textColor: '#ffffff',
  },
  KAIST: {
    id: 'KAIST',
    name: '한국과학기술원',
    shortName: 'KAIST',
    logoText: 'K',
    logoUrl: '/kaist.png',
    color: '#1487C8',
    bgLight: '#EBF6FC',
    textColor: '#ffffff',
  },
  GIST: {
    id: 'GIST',
    name: '광주과학기술원',
    shortName: 'GIST',
    logoText: 'G',
    logoUrl: '/gist.png',
    color: '#DF3128',
    bgLight: '#FDF1F0',
    textColor: '#ffffff',
  },
  DGIST: {
    id: 'DGIST',
    name: '대구경북과학기술원',
    shortName: 'DGIST',
    logoText: 'D',
    logoUrl: '/dgist.png',
    color: '#0BBFF2',
    bgLight: '#E8F9FE',
    textColor: '#ffffff',
  },
  UNIST: {
    id: 'UNIST',
    name: '울산과학기술원',
    shortName: 'UNIST',
    logoText: 'U',
    logoUrl: '/unist.png',
    color: '#001B54',
    bgLight: '#E8EDF6',
    textColor: '#ffffff',
  },
  KENTECH: {
    id: 'KENTECH',
    name: '한국에너지공과대학교',
    shortName: 'KENTECH',
    logoText: 'KE',
    logoUrl: '/kentech.png',
    color: '#00316C',
    bgLight: '#EBF1F7',
    textColor: '#ffffff',
  },
};
